import type { RegistrySource } from "./types";

/**
 * The source catalog is deliberately broader than the active connectors.
 * `active` means the endpoint is machine-read today; `registered` means the
 * publisher is authoritative and queued for a dedicated adapter.
 */
export const officialSources: RegistrySource[] = [
  {
    id: "github",
    name: "GitHub repositories",
    publisher: "GitHub",
    region: "global",
    kind: "repository",
    trustTier: "canonical",
    automationStatus: "active",
    connector: "github",
    url: "https://github.com",
    apiUrl: "https://api.github.com",
    scope: ["agents", "models", "robots", "hardware"],
    cadence: "daily"
  },
  {
    id: "huggingface",
    name: "Hugging Face Hub",
    publisher: "Hugging Face",
    region: "global",
    kind: "registry",
    trustTier: "canonical",
    automationStatus: "active",
    connector: "huggingface",
    url: "https://huggingface.co",
    apiUrl: "https://huggingface.co/api",
    scope: ["models", "agents", "robots"],
    cadence: "daily"
  },
  {
    id: "arxiv",
    name: "arXiv",
    publisher: "Cornell Tech",
    region: "global",
    kind: "research",
    trustTier: "canonical",
    automationStatus: "registered",
    connector: "rss",
    url: "https://arxiv.org",
    apiUrl: "https://export.arxiv.org/api/query",
    scope: ["research", "agents", "models", "robots"],
    cadence: "daily"
  },
  {
    id: "pypi",
    name: "Python Package Index",
    publisher: "Python Packaging Authority",
    region: "global",
    kind: "registry",
    trustTier: "canonical",
    automationStatus: "registered",
    connector: "json-api",
    url: "https://pypi.org",
    apiUrl: "https://pypi.org/pypi/{project}/json",
    scope: ["agents", "robots"],
    cadence: "daily"
  },
  {
    id: "npm",
    name: "npm Registry",
    publisher: "npm",
    region: "global",
    kind: "registry",
    trustTier: "canonical",
    automationStatus: "registered",
    connector: "json-api",
    url: "https://www.npmjs.com",
    apiUrl: "https://registry.npmjs.org/{package}",
    scope: ["agents", "robots"],
    cadence: "daily"
  },
  {
    id: "open-robotics",
    name: "Open Robotics Blog",
    publisher: "Open Robotics",
    region: "us",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.openrobotics.org/blog",
    scope: ["robots", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "nvidia-developer",
    name: "NVIDIA Technical Blog",
    publisher: "NVIDIA",
    region: "us",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "active",
    connector: "rss",
    url: "https://developer.nvidia.com/blog/",
    feedUrl: "https://developer.nvidia.com/blog/feed/",
    scope: ["agents", "models", "robots", "hardware", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "openai-news",
    name: "OpenAI News",
    publisher: "OpenAI",
    region: "us",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://openai.com/news/",
    scope: ["agents", "models", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "anthropic-news",
    name: "Anthropic Newsroom",
    publisher: "Anthropic",
    region: "us",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.anthropic.com/news",
    scope: ["agents", "models", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind News",
    publisher: "Google DeepMind",
    region: "us",
    kind: "research",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://deepmind.google/discover/blog/",
    scope: ["agents", "models", "robots", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "meta-ai",
    name: "Meta AI Blog",
    publisher: "Meta",
    region: "us",
    kind: "research",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://ai.meta.com/blog/",
    scope: ["agents", "models", "robots", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "microsoft-research",
    name: "Microsoft Research Blog",
    publisher: "Microsoft",
    region: "us",
    kind: "research",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.microsoft.com/en-us/research/blog/",
    scope: ["agents", "models", "robots", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "allen-ai",
    name: "Ai2 Blog",
    publisher: "Allen Institute for AI",
    region: "us",
    kind: "research",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://allenai.org/blog",
    scope: ["agents", "models", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "qwen-blog",
    name: "Qwen Blog",
    publisher: "Alibaba Cloud / Qwen Team",
    region: "cn",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://qwenlm.github.io/blog/",
    scope: ["agents", "models", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "deepseek",
    name: "DeepSeek Official",
    publisher: "DeepSeek",
    region: "cn",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.deepseek.com/",
    scope: ["agents", "models", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "zhipu-ai",
    name: "Zhipu AI Official",
    publisher: "Zhipu AI",
    region: "cn",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.zhipuai.cn/",
    scope: ["agents", "models", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "moonshot-ai",
    name: "Moonshot AI Official",
    publisher: "Moonshot AI",
    region: "cn",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.moonshot.cn/",
    scope: ["agents", "models", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "baidu-ai",
    name: "Baidu AI Official",
    publisher: "Baidu",
    region: "cn",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://ai.baidu.com/",
    scope: ["agents", "models", "robots", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "tencent-hunyuan",
    name: "Tencent Hunyuan",
    publisher: "Tencent",
    region: "cn",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://hunyuan.tencent.com/",
    scope: ["agents", "models", "robots", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "bytedance-seed",
    name: "ByteDance Seed",
    publisher: "ByteDance",
    region: "cn",
    kind: "research",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://seed.bytedance.com/en/",
    scope: ["agents", "models", "robots", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "huawei-noah",
    name: "Huawei Noah's Ark Lab",
    publisher: "Huawei",
    region: "cn",
    kind: "research",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.noahlab.com.hk/",
    scope: ["agents", "models", "robots", "hardware", "research"],
    cadence: "weekly"
  },
  {
    id: "minimax",
    name: "MiniMax Official",
    publisher: "MiniMax",
    region: "cn",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.minimaxi.com/",
    scope: ["agents", "models", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "unitree",
    name: "Unitree News",
    publisher: "Unitree Robotics",
    region: "cn",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.unitree.com/news/",
    scope: ["robots", "hardware", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "ubtech",
    name: "UBTECH News",
    publisher: "UBTECH Robotics",
    region: "cn",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.ubtrobot.com/en/news",
    scope: ["robots", "hardware", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "agibot",
    name: "AgiBot Official",
    publisher: "AgiBot",
    region: "cn",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.zhiyuan-robot.com/",
    scope: ["robots", "hardware", "research", "company-news"],
    cadence: "daily"
  },
  {
    id: "pollen-robotics",
    name: "Pollen Robotics",
    publisher: "Pollen Robotics",
    region: "eu",
    kind: "newsroom",
    trustTier: "official",
    automationStatus: "registered",
    connector: "html",
    url: "https://www.pollen-robotics.com/",
    scope: ["robots", "hardware", "research", "company-news"],
    cadence: "weekly"
  },
  {
    id: "huggingface-lerobot",
    name: "LeRobot",
    publisher: "Hugging Face",
    region: "global",
    kind: "repository",
    trustTier: "official",
    automationStatus: "registered",
    connector: "github",
    url: "https://github.com/huggingface/lerobot",
    scope: ["robots", "models", "research"],
    cadence: "daily"
  }
];

export function getActiveSources(): RegistrySource[] {
  return officialSources.filter((source) => source.automationStatus === "active");
}

export function getSourcesByRegion(region: RegistrySource["region"]): RegistrySource[] {
  return officialSources.filter((source) => source.region === region);
}
